[tool.poetry]
name = "easyflake"
version = "0.1.0"
description = ""
authors = ["tsuperis <tsuperis@gmail.com>"]
readme = "README.md"
packages = [{include = "easyflake", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.8"
toml = "^0.10.2"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
flake8 = "~5.0.4"
isort = "^5.12.0"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
freezegun = "^1.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
